# Objetos basicos

#### Manejo de listas

In [2]:
x = [1,2,3]
y = [4]

In [3]:
x + y

[1, 2, 3, 4]

In [4]:
x.append(3)
display(x)

[1, 2, 3, 3]

In [5]:
x.extend([5])
display(x)

[1, 2, 3, 3, 5]

In [6]:
[2*x for x in x]

[2, 4, 6, 6, 10]

In [7]:
[x for x in x if x == 3]

[3, 3]

In [8]:
[x-1 for x in x if x == 3]

[2, 2]

In [9]:
[x == 3 for x in x]

[False, False, True, True, False]

In [12]:
x[0:3]

[1, 2, 3]

In [13]:
x[0:3]

[1, 2, 3]

In [14]:
x[:]

[1, 2, 3, 3, 5]

In [15]:
x[:-2]

[1, 2, 3]

###### Tuplas

In [29]:
a = ('a','b','c')
b = ('d','e')

In [30]:
[x for x in a]

['a', 'b', 'c']

In [31]:
a + b

('a', 'b', 'c', 'd', 'e')

In [32]:
a[-1]

'c'

###### Conjuntos

In [16]:
setA = set(['a','b','c','a'])
setB = set(['b','d'])

In [17]:
setA & setB

{'b'}

In [18]:
setA | setB

{'a', 'b', 'c', 'd'}

In [19]:
setA - setB

{'a', 'c'}

In [20]:
(setA - setB) | (setB - setA) 

{'a', 'c', 'd'}

In [22]:
#setA[1]

###### Diccionarios

In [23]:
diccionario = {'a':'b','c':['a,b','c','d'],'d':('a','b')}

In [24]:
diccionario['a']

'b'

In [25]:
diccionario['c']

['a,b', 'c', 'd']

In [26]:
diccionario['d']

('a', 'b')

In [35]:
diccionario.keys()

dict_keys(['a', 'c', 'd'])

###### Tipos

In [27]:
type(diccionario)

dict

In [33]:
type(a)

tuple

In [34]:
type(x)

list

###### Iteraciones

In [36]:
for i in ['a','b','c']:
    print(i)

a
b
c


In [31]:
for i in enumerate(['a','b','c']):
    print(i)

(0, 'a')
(1, 'b')
(2, 'c')


In [32]:
for i, letra in enumerate(['a','b','c']):
    print(i)
    print(letra)

0
a
1
b
2
c


In [33]:
for i in range(2,20):
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [34]:
for i in range(2,20,10):
    print(i)

2
12


# Funciones

In [43]:
def funcion(x):
    return x*2

In [44]:
funcion(2)

4

In [46]:
def funcion(*args):
    return sum(args)

In [48]:
funcion(2,3,4,5)

14

In [50]:
#funcion([2,3,4])
funcion(*[2,3,4])

9

In [51]:
funcionlambda = lambda y: y**2
funcionlambda2 = lambda y: sum(y)
funcionlambda3 = lambda *args: sum(args)

In [52]:
funcionlambda(2)

4

In [53]:
#funcionlambda([2,2])
funcionlambda2([2,2])

4

In [54]:
funcionlambda3(2,2)

4

# Clases

In [65]:
class Clase1:
    def __init__(self):
        self.arg = 'a'
    def funcion(self):
        return 'b'

In [66]:
R = Clase1()

In [67]:
R.arg

'a'

In [68]:
R.funcion()

'b'

In [69]:
class NumeroComplejo:
    def __init__(self, r=0, i=0):
        self.real = r
        self.imag = i

    def get_data(self):
        print(f'{self.real}+{self.imag}j')

In [70]:
NC1 = NumeroComplejo(2,3)
NC2 = NumeroComplejo(2,3)

In [71]:
NC1

In [72]:
NC1.get_data()

2+3j


In [73]:
NC2.get_data()

2+3j


In [75]:
#NC1 + NC2

In [78]:
class NumeroComplejo:
    def __init__(self, r=0, i=0):
        self.real = r
        self.imag = i

    def get_data(self):
        print(f'{self.real}+{self.imag}j')
    
    def complexsum(self,Numero):
        self.real = self.real + Numero.real
        self.imag = self.imag + Numero.imag
        return self

In [79]:
NC1 = NumeroComplejo(2,3)
NC2 = NumeroComplejo(2,3)

In [80]:
NC1.complexsum(NC2).get_data()

4+6j


# Matrices (Numpy)

In [81]:
import numpy as np

In [83]:
np.__version__

'1.19.0'

In [84]:
np.array([2,3,4])

array([2, 3, 4])

In [85]:
np.array([2,3,4]) + 1

array([3, 4, 5])

In [86]:
np.array([2,3,4]) + np.array([1]) 

array([3, 4, 5])

In [87]:
np.array([2,3,4])*np.array([[1],[2],[3]]) 

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

In [88]:
Matrix = np.array([2,3,4])*np.array([[1],[2],[3]]) 

In [89]:
Matrix[0:3,0]

array([2, 4, 6])

In [90]:
Matrix[0:2,-1]

array([4, 8])

In [91]:
np.hstack([Matrix,np.array([[1],[2],[3]])])

array([[ 2,  3,  4,  1],
       [ 4,  6,  8,  2],
       [ 6,  9, 12,  3]])

In [92]:
np.vstack([Matrix,np.array([1,2,3])])

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12],
       [ 1,  2,  3]])